### ISSUE TITLE
Error while executing bap.run

### ISSUE THREAD

**Issue by GodsJoy** [BinaryAnalysisPlatform/bap-python#8]
I got the following error while executing bap.run on a node binary. I was told on bap forum that it is a bug in bap:

Traceback (most recent call last):
  File "extract_bpir.py", line 406, in <module>
    main()
  File "extract_bpir.py", line 402, in main
    proj = bap.run(sys.argv[1], ['--no-byteweight'])
  File "/usr/local/lib/python2.7/dist-packages/bap/bap.py", line 124, in run
    return parser['load'](out)
  File "/usr/local/lib/python2.7/dist-packages/bap/bir.py", line 367, in loads
    return noeval_parser.parser(s)
  File "/usr/local/lib/python2.7/dist-packages/bap/noeval_parser.py", line 328, in parser
    result = _parser(input_str, logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/bap/noeval_parser.py", line 291, in _parser
    assert len(stk) == 1
AssertionError

[nodeO2.tar.gz](https://github.com/BinaryAnalysisPlatform/bap-python/files/1968269/nodeO2.tar.gz)

**Comment by ivg** [comment]
Just in case, if you had a smaller file that triggers this error, then please submit it.

**Comment by GodsJoy** [comment]
That is the smaller file, the second one is bigger.
